# Site settings
title: "Thoughts, Experiences and Pure Poetry"
author: "Márcio Vilela Fontes"
description: "This is a blog about thoughts, experiences and pure poetry. "
# keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am a Informatics Engineering student at the <a href='http://www.fe.up.pt'>Faculty of Engineering</a>, University of Porto and a writer. Here you can find my <a href='/assets/cv.pdf'>Résumé</a>. For more info please visit my personal <a href='https://www.inesctec.pt'>website</a>"
colophon: "© All rights owned by Hugo Sereno Ferreira."

baseurl: ""
url: "http://marciofontes.pt"

instagram_username: marcio.fvfontes
github_username: mfvfontes
linkedin_username: mfvfontes
facebook_username: mfvfontes

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

gems:
- jekyll-sitemap
