# Site settings
title: "Thoughts "
author: "Márcio Vilela Fontes"
description: "This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am a Professor of Software Engineering at the <a href='http://www.fe.up.pt'>Faculty of Engineering</a>, University of Porto and Senior Researcher at <a href='https://www.inesctec.pt'>INESC TEC</a>. Here you can find my <a href='/assets/thesis.pdf'>PhD Thesis</a> and my <a href='/assets/cv.pdf'>Résumé</a>."
colophon: "© All rights owned by Hugo Sereno Ferreira."

baseurl: ""
url: "http://marciofontes.pt"

instagram_username: marcio.fvfontes
github_username: mfvfontes
linkedin_username: mfvfontes
facebook_username: mfvfontes

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

gems:
- jekyll-sitemap
